### ISSUE TITLE
Error when uploading large flight

### ISSUE THREAD

**Issue by AffiFPV** [dbrgn/flugbuech#116]
I get a nginx 413 error when uploading a big flight (my longest yet (5:30h) when clicking "Submit". The IGC which produces the error was recorded with my Skydrop, the IGC out of XCTrack is a bit smaller (761KB vs 846KB) and gets accepted without any issue. I also tried to reproduce the error and "stole" a random big IGC of someone on XContest (I took this one: https://www.xcontest.org/world/en/flights/detail:Neyo996/14.08.2022/07:08) uploading this produces a "Could not process IGC file: Error: HTTP 413" Pop-Up (mine just resulted in a blank error page).
I've attached both my Skybean and my XCTrack Logs.

[big_flight_413.zip](https://github.com/dbrgn/flugbuech/files/9352596/big_flight_413.zip)
Edit: Browser is Firefox 103.0.2 (64-Bit)

**Comment by dbrgn** [comment]
Interesting, thanks for the report, and congrats for your long flight!

The limit configured by the web framework is currently set to 3 MiB, which should be sufficient even for 12h flights. However, the default limit by Nginx seems to be 1 MiB. I increased it to 8 MiB, can you test again?

**Comment by AffiFPV** [comment]
Yes it works now, also the 1.5MB track I took of Xcontest works now. Thank You!
